#!/bin/sh /etc/rc.common 

start() {

    echo "interface eth0
{
request domain-name-servers ;
request domain-name ;

script \"/etc/wide-dhcpv6/dhcp6c-script\"
};
" > 

	/usr/sbin/dhcp6c -c $config_file $debug_option $client_ifname
	
	sleep 3
	#ACTION=start /sbin/hotplug-call dhcp6c
	
	return 0
	
}

stop() {

	logger stopping dhcp6c
	rm -f /var/etc/dhcp6c.conf
	kill -TERM `cat /var/run/dhcp6c.pid`
	#ACTION=stop /sbin/hotplug-call dhcp6c
	return 0
	
}


