#!/bin/sh /etc/rc.common
BIN=/usr/sbin/stats
PID_FILE=/var/run/stats.pid
. /etc/network.sh
START=50
log_msg="STATS-server"
start () {
    [ $(nvram show stats_rule 0 enable) = "1" ] && {
        local platform="$(nvram get platform)"
        [ "$platform" = "AXA" -o "$platform" = "AXM" ] && {
            nvram set stats_type="thp"
            nvram set stats_ifname="br0"
            nvram set stats_interval="60"
        }
        $BIN || err=1 
    }
    return $err
}
